### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by sobolevn** [wunsh/elixir-docs-ru#4]
Hi, everyone! Thanks for your efforts and time!

I would like to propose some changes in planing. I would like to help you with the translation, but I don't want to do the same job twice (no one wants that). 

So, I guess we should mark somehow that some topic is "work in progress".
I recommend to use github issues for this task. 

What do you think? 

Thanks!

**Comment by rtrv** [comment]
Hi. Nice idea and good solution, we could create issues for all undone topics and mark them WIP when smb starts the translation. @jarosluv what do you think?

**Comment by jarosluv** [comment]
@sobolevn @rtrv 

Hi! Thanks for your proposal!

I have same idea too, but we need to add Readme with contributing guide first. I can do this tomorrow. All agree?

**Comment by jarosluv** [comment]
Done!

Please, see https://github.com/wunsh/elixir-docs-ru/issues/6 and [README.md](https://github.com/wunsh/elixir-docs-ru/blob/master/README.md).
